############################################################
# Site settings
############################################################
title                   : "Chris Mavrommatis"
email                   : your-email@example.com
description             : >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
baseurl                 : "" # the subpath of your site, e.g. /blog
url                     : "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username        : jekyllrb
github_username         : jekyll


############################################################
# Where things are
############################################################
source              : ./src
destination         : _site
collections_dir     : collections
plugins_dir         : _plugins       # takes an array of strings and loads plugins in that order
layouts_dir         : _layouts
includes_dir        : _includes
data_dir            : _data
sass:
  sass_dir          : _sass
  cache             : false
  style             : compressed
collections:
  posts:
    output          : true
    permalink       : /blog/post/:slug

############################################################
# Handling Reading
############################################################
safe                : false
include             : 
  - ".htaccess"
exclude             : 
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
keep_files          : [".git", ".svn"]
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
strict_front_matter : false

############################################################
# Filtering Content
############################################################
show_drafts         : false
limit_posts         : 0
future              : false
unpublished         : false

############################################################
# Serving
############################################################
detach              : false
port                : 4002
host                : 127.0.0.1
baseurl             : ""    # does not include hostname
show_dir_listing    : false
disable_disk_cache  : true

############################################################
# Conversion
############################################################
markdown            : kramdown
highlighter         : rouge
lsi                 : false
excerpt_separator   : "\n\n"
incremental         : false

############################################################
# Outputting
############################################################
permalink           : date        #pretty
paginate_path       : /page:num
timezone            : "Europe/Athens"       
quiet               : false
verbose             : false
defaults            : []
liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false

############################################################
# Markdown Processors
############################################################
kramdown:
  auto_ids          : false
  entity_output     : as_char
  toc_levels        : '1..6'
  smart_quotes      : lsquo,rsquo,ldquo,rdquo
  input             : GFM
  hard_wrap         : false
  footnote_nr       : 1
  show_warnings     : false
  parse_block_html  : true

############################################################
# Plugins
############################################################
gems                : []
whitelist           : []
plugins             : 
  - jekyll-tidy
  - jekyll-paginate-v2

############################################################
# Front Matter Defaults
############################################################
defaults:
  -
    scope:
      path           : ""  
      type           : "pages"
    values:
      layout         : "default"
      title          : "NOTITLE"
      sitemap        : null
      isSitemap      : false
  -    
    scope:
      path           : "pages/**"  
      type           : "pages"
    values:
      sitemap:
        lastmod		 : "current"
        changefreq	 : "weekly"
        priority	 : 1.0
  - 
    scope:
      type           : "posts"
      path           : ""
    values:
      layout         : "default"
      title          : "NOTITLE"
      sitemap        : null
      main_img       : "https://picsum.photos/400/150"

  - 
    scope:
      path           : "collections/_posts"
      type           : "posts"
    values:
      sitemap:
        changefreq	 : "monthly"
        priority	 : 1.0


  -
    scope:
      path           : "feeds/sitemaps/**"
      type           : "pages"
    values:
      layout         : null
      isSitemap      : true
      
############################################################
################### END OF BASE CONFIG #####################
############################################################


############################################################
# jekyll-tidy
############################################################
jekyll_tidy:
  exclude       : []       # an array of files to exclude from tidying.
  ignore_env    : null     # a JEKYLL_ENV string on which to skip tidying entirely.
  compress_html : false    # a flag for whether or not to compress the HTML output

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
############################################################
pagination:
  enabled         : true                                  # Site-wide kill switch, disabled here it doesn't run at all 
  debug           : false                                 # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  collection      : 'posts'                               # The default document collection to paginate if nothing is specified ('posts' is default)
  per_page        : 4                                    # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  permalink       : '/page:num/'                          # The permalink structure for the paginated pages (this can be any level deep)
  title           : ':title - Page :num'                  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  limit           : 0                                     # Limit how many pagenated pages to create (default: 0, means all)
  sort_field      : 'date'                                # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_reverse    : true                                  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  category        : 'posts'                               # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  tag             : ''                                    # Optional, the default tag to use, omit to disable
  locale          : ''                                    # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
                                                          # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  trail:                                                 
   before         : 2                                     # Optional,omit or set both before and after to zero to disable.
   after          : 2                                     # Controls how the pagination trail for the paginated pages look like. 
  extension       : html                                  # Optional, the default file extension for generated pages (e.g html, json, xml).
                                                          # Internally this is set to html by default
  indexpage       : 'index'                               # Optional, the default name of the index file for generated pages (e.g. 'index.html')
                                                          # Without file extension
